version: '2'
services:
  php:
    container_name: ${APP_NAME}-php
    build: .
    volumes:
     - ./src:/var/www/wmvisit
     - /var/www/wmvisit/vendor
    ports:
     - ${HTTP_PORT}:80
     - ${HTTPS_PORT}:443
volumes:
  data:
    driver: local