version: '2'
services:
  php:
    container_name: ${APP_NAME}-php
    build: .
    links:
      - redis
    volumes:
     - ./src:/var/www/wmvisit
     - /var/www/wmvisit/vendor
    ports:
     - ${HTTP_PORT}:80
     - ${HTTPS_PORT}:443
  redis:
    container_name: ${REDIS_NAME}-redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - /srv/docker/redis:/var/lib/redis
volumes:
  data:
    driver: local